#!/bin/sh -x
set -eu

ds="$(date +%d.%m.%Y)"
rm named/ЗКМ_*.kml
newname="ЗКМ_${ds}.kml"
printf "%s\n" "$newname" > named/latest
cp "./MGR.kml" "./named/${newname}"


make_redirector() {
    url="$1"
    title="$2"
    cat <<_EOF
<!DOCTYPE html><html><head>
<meta http-equiv="refresh" content="1; url='${url}'" />
</head><body>
<p><a href="${url}">${title}</a></p>
</body></html>
_EOF
}

ROOT_UQ="https%3A%2F%2Fraw.githubusercontent.com%2Favsovetov%2Fmgr%2Fmaster%2F"
ROOT_CYCLING_UQ="https%3A%2F%2Fraw.githubusercontent.com%2Favsovetov%2Fmgr%2Fcycling%2F"
base_url="https://nakarte.me/#m=11/55.71686/37.66525&l=O&nktu="
trackonly_url="${base_url}${ROOT_UQ}named%2F${newname}"
# Туалеты, Памятники, Храмы, Достопримечательности, Переходы
extra_tracks_url_piece="\
/${ROOT_UQ}originals%2F%D0%A2%D1%83%D0%B0%D0%BB%D0%B5%D1%82%D1%8B.kml\
/${ROOT_UQ}originals%2F%D0%9F%D0%B0%D0%BC%D1%8F%D1%82%D0%BD%D0%B8%D0%BA%D0%B8.kml\
/${ROOT_UQ}originals%2F%D0%A5%D1%80%D0%B0%D0%BC%D1%8B.kml\
/${ROOT_UQ}originals%2F%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8.kml\
/${ROOT_UQ}originals%2F%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D1%8B.kml\
"
main_url="\
${trackonly_url}\
${extra_tracks_url_piece}\
/${ROOT_UQ}originals%2F%D0%9C%D0%B5%D1%82%D1%80%D0%BE%2C%20%D0%9C%D0%A6%D0%9A%2C%20%D0%9C%D0%A6%D0%94.kml\
"

make_redirector "$main_url" "Зелёное Кольцо Моксвы НаКарте" > ./totrack/index.html
make_redirector "$trackonly_url" "Зелёное Кольцо Моксвы (только трек) НаКарте" > ./totrackonly/index.html

cycling_latest_name="$(curl -fs 'https://raw.githubusercontent.com/avsovetov/mgr/cycling/named_cycling/latest')"
cycling_track_url="${base_url}${ROOT_CYCLING_UQ}named_cycling%2F${cycling_latest_name}"
# + МЦК_МЦД (без метро), + Велопримечания, + Велоальтернативы
cycling_url="\
${cycling_track_url}\
/${ROOT_UQ}points%2F%D0%9C%D0%A6%D0%9A_%D0%9C%D0%A6%D0%94.kml\
/${ROOT_UQ}originals%2F%D0%9F%D0%B5%D1%80%D0%B5%D1%85%D0%BE%D0%B4%D1%8B.kml\
/${ROOT_CYCLING_UQ}%D0%92%D0%B5%D0%BB%D0%BE%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F.kml\
/${ROOT_CYCLING_UQ}%D0%92%D0%B5%D0%BB%D0%BE%D0%B0%D0%BB%D1%8C%D1%82%D0%B5%D1%80%D0%BD%D0%B0%D1%82%D0%B8%D0%B2%D1%8B.kml\
"
make_redirector "$cycling_url" "Зелёное Кольцо Москвы (Вело) НаКарте" > ./tocycling/index.html
